INITIATED_STEP = "INITIATED_STEP"
BALANCE_SHEET_REQUESTED_STEP = "BALANCE_SHEET_REQUESTED_STEP"
RETRIEVED_BALANCE_SHEET_STEP = "RETRIEVED_BALANCE_SHEET_STEP"
APPLICATION_REVIEWED_STEP = "APPLICATION_REVIEWED_STEP"
DECISION_REQUESTED_STEP = "DECISION_REQUESTED_STEP"
DECISION_RESULT_SENT_TO_USER_STEP = "DECISION_RESULT_SENT_TO_USER_STEP"

BUSINESS_LOAN_STEPS = [
    (INITIATED_STEP, "Initiated"),
    (BALANCE_SHEET_REQUESTED_STEP, "Balance sheet requested"),
    (RETRIEVED_BALANCE_SHEET_STEP, "Retrieved balance sheet"),
    (APPLICATION_REVIEWED_STEP, "Application reviewed"),
    (DECISION_REQUESTED_STEP, "Decision requested"),
    (DECISION_RESULT_SENT_TO_USER_STEP, "Decision result sent to user"),
]
