# Generated by Django 4.2.1 on 2023-05-07 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplicationTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('steps', models.CharField(choices=[('INITIATED_STEP', 'Initiated'), ('BALANCE_SHEET_REQUESTED_STEP', 'Balance sheet requested'), ('RETRIEVED_BALANCE_SHEET_STEP', 'Retrieved balance sheet'), ('APPLICATION_REVIEWED_STEP', 'Application reviewed'), ('DECISION_REQUESTED_STEP', 'Decision requested'), ('DECISION_RESULT_SENT_TO_USER_STEP', 'Decision result sent to user')], max_length=50)),
                ('application_details', models.JSONField(default=dict)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_loan_application.applicant')),
            ],
        ),
    ]
